# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master

git:
  depth: 10

language: node_js

node_js:
  - "stable"
